apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: phonebook
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30000
